In [228]:
import yfinance as yf

stock_tickers =['META', 'NFLX', 'TSLA']

database = yf.download(stock_tickers,start='2012-01-01',end ='2021-12-30')
database = database['Adj Close']
data = database.dropna().pct_change(1).dropna()
data

[*********************100%***********************]  3 of 3 completed

Ticker                         META      NFLX      TSLA
Date
2012-05-21 00:00:00+00:00 -0.109861  0.025443  0.043904
2012-05-22 00:00:00+00:00 -0.089039 -0.056175  0.070559
2012-05-23 00:00:00+00:00  0.032258  0.062029  0.007143
2012-05-24 00:00:00+00:00  0.032188 -0.022806 -0.023855
2012-05-25 00:00:00+00:00 -0.033909 -0.000711 -0.015522
...                             ...       ...       ...
2021-12-22 00:00:00+00:00 -0.011221  0.015407  0.074947
2021-12-23 00:00:00+00:00  0.014495 -0.000244  0.057619
2021-12-27 00:00:00+00:00  0.032633 -0.001580  0.025248
2021-12-28 00:00:00+00:00  0.000116 -0.003931 -0.005000
2021-12-29 00:00:00+00:00 -0.009474 -0.000278 -0.002095

[2419 rows x 3 columns]

In [229]:
data_ohlcv = yf.download(stock_tickers,start='2012-01-01',end ='2021-12-30').dropna()
data_ohlcv

[*********************100%***********************]  3 of 3 completed

Price                       Adj Close                               Close  \
Ticker                           META        NFLX        TSLA        META
Date
2012-05-18 00:00:00+00:00   38.115238    9.994286    1.837333   38.230000
2012-05-21 00:00:00+00:00   33.927845   10.248571    1.918000   34.029999
2012-05-22 00:00:00+00:00   30.906942    9.672857    2.053333   31.000000
2012-05-23 00:00:00+00:00   31.903942   10.272857    2.068000   32.000000
2012-05-24 00:00:00+00:00   32.930851   10.038571    2.018667   33.029999
...                               ...         ...         ...         ...
2021-12-22 00:00:00+00:00  329.458038  614.239990  336.290009  330.450012
2021-12-23 00:00:00+00:00  334.233673  614.090027  355.666656  335.239990
2021-12-27 00:00:00+00:00  345.140808  613.119995  364.646667  346.179993
2021-12-28 00:00:00+00:00  345.180725  610.710022  362.823334  346.220001
2021-12-29 00:00:00+00:00  341.910583  610.539978  362.063324  342.940002

Price                                                    High              \
Ticker                           NFLX        TSLA        META        NFLX
Date
2012-05-18 00:00:00+00:00    9.994286    1.837333   45.000000   10.392857
2012-05-21 00:00:00+00:00   10.248571    1.918000   36.660000   10.312857
2012-05-22 00:00:00+00:00    9.672857    2.053333   33.590000   10.342857
2012-05-23 00:00:00+00:00   10.272857    2.068000   32.500000   10.307143
2012-05-24 00:00:00+00:00   10.038571    2.018667   33.209999   10.241429
...                               ...         ...         ...         ...
2021-12-22 00:00:00+00:00  614.239990  336.290009  334.510010  614.820007
2021-12-23 00:00:00+00:00  614.090027  355.666656  336.670013  616.880005
2021-12-27 00:00:00+00:00  613.119995  364.646667  347.869995  615.000000
2021-12-28 00:00:00+00:00  610.710022  362.823334  352.709991  618.409973
2021-12-29 00:00:00+00:00  610.539978  362.063324  349.690002  613.979980

Price                                         Low                          \
Ticker                           TSLA        META        NFLX        TSLA
Date
2012-05-18 00:00:00+00:00    1.897333   38.000000    9.337143    1.788667
2012-05-21 00:00:00+00:00    1.950667   33.000000    9.650000    1.808000
2012-05-22 00:00:00+00:00    2.089333   30.940001    9.607143    2.000000
2012-05-23 00:00:00+00:00    2.070000   31.360001    9.595714    1.966667
2012-05-24 00:00:00+00:00    2.083333   31.770000    9.928571    1.979333
...                               ...         ...         ...         ...
2021-12-22 00:00:00+00:00  338.553345  328.260010  602.630005  319.016663
2021-12-23 00:00:00+00:00  357.660004  328.359985  607.570007  332.519989
2021-12-27 00:00:00+00:00  372.333344  338.010010  609.250000  356.906677
2021-12-28 00:00:00+00:00  373.000000  345.200012  609.690002  359.473328
2021-12-29 00:00:00+00:00  368.000000  341.640015  604.679993  354.713318

Price                            Open                               Volume  \
Ticker                           META        NFLX        TSLA         META
Date
2012-05-18 00:00:00+00:00   42.049999   10.328571    1.891333  573576400.0
2012-05-21 00:00:00+00:00   36.529999    9.978571    1.838667  168192700.0
2012-05-22 00:00:00+00:00   32.610001   10.257143    2.006667  101786600.0
2012-05-23 00:00:00+00:00   31.370001    9.638571    2.037333   73600000.0
2012-05-24 00:00:00+00:00   32.950001   10.217143    2.083333   50237200.0
...                               ...         ...         ...          ...
2021-12-22 00:00:00+00:00  333.799988  603.359985  321.886658   16764600.0
2021-12-23 00:00:00+00:00  330.100006  616.400024  335.600006   13987700.0
2021-12-27 00:00:00+00:00  338.850006  615.000000  357.890015   17795000.0
2021-12-28 00:00:00+00:00  346.630005  614.950012  369.829987   16637600.0
2021-12-29 00:00:00+00:00  346.910004  610.710022  366.213318   10747000.0

Price
Ticker                         NFLX      TSLA
Date
2012-05-18 00:00:00+00:00  29415400  24247500
2012-05-21 00:00:00+00:00  25143300  22128000
2012-05-22 00:00:00+00:00  40014800  35493000
2012-05-23 00:00:00+00:00  44100000  18306000
2012-05-24 00:00:00+00:00  20742400  16134000
...                             ...       ...
2021-12-22 00:00:00+00:00   2335700  93634200
2021-12-23 00:00:00+00:00   1621100  92713200
2021-12-27 00:00:00+00:00   2061500  71145900
2021-12-28 00:00:00+00:00   1882800  60324000
2021-12-29 00:00:00+00:00   1287200  56154000

[2420 rows x 18 columns]

In [230]:
import pandas as pd
import numpy as np
from tqdm import tqdm

def find_timestamp_extremum(data, df_lowest_timeframe):
    """
    :params: data(highest timeframe OHLCV data),
             df_lowest_timeframe (lowest timeframe OHLCV data)
    :return: data with three new columns: Low_time (TimeStamp), 
             High_time (TimeStamp), High_first (Boolean)
    """
    # Create a copy to avoid modifying the original DataFrame
    data = data.copy()
    
    # Identify stock tickers (assumes column names like 'High_STOCK')
    stocks = list(set(col.split('_')[1] for col in data.columns if '_' in col))
    
    # Prepare new columns with explicit datetime type
    data["Low_time"] = pd.NaT
    data["High_time"] = pd.NaT
    data["First"] = np.nan

    # Loop to find out which of the Take Profit and Stop Loss appears first
    for i in tqdm(range(len(data) - 1)):
        # Extract values from the lowest timeframe dataframe
        start = data.iloc[i:i + 1].index[0]
        end = data.iloc[i + 1:i + 2].index[0]
        
        # Initialize lists to store high and low times for all stocks
        high_times = []
        low_times = []
        
        # Process each stock
        for stock in stocks:
            try:
                # Try to find high and low columns for each stock
                high_col = [col for col in df_lowest_timeframe.columns if f'High_{stock}' in col][0]
                low_col = [col for col in df_lowest_timeframe.columns if f'Low_{stock}' in col][0]
                
                # Extract rows for this time period
                row_lowest_timeframe = df_lowest_timeframe.loc[start:end].iloc[:-1]
                
                # Find high and low times
                high = row_lowest_timeframe[high_col].idxmax()
                low = row_lowest_timeframe[low_col].idxmin()
                
                high_times.append(high)
                low_times.append(low)
            
            except Exception as e:
                print(f"Error processing stock {stock}: {e}")
                continue
        
        # If we found any high/low times
        if high_times and low_times:
            # Get the earliest high and lowest low
            earliest_high = min(high_times)
            earliest_low = min(low_times)
            
            # Explicitly convert and set times
            data.at[start, "Low_time"] = pd.Timestamp(earliest_low).tz_localize(None)
            data.at[start, "High_time"] = pd.Timestamp(earliest_high).tz_localize(None)
        else:
            # Fallback if no times found
            data.at[start, "Low_time"] = pd.Timestamp(start)
            data.at[start, "High_time"] = pd.Timestamp(start)

    # Find out which appears first
    data.loc[data["High_time"] > data["Low_time"], "First"] = 1
    data.loc[data["High_time"] < data["Low_time"], "First"] = 2
    data.loc[data["High_time"] == data["Low_time"], "First"] = 0

    # Verify the number of rows without both TP and SL on same time
    percentage_garbage_row = len(data.loc[data["First"] == 0].dropna()) / len(data) * 100
    print(f"WARNINGS: Garbage row: {percentage_garbage_row:.2f}%")

    # We delete the last row because we can't find the extremum
    data = data.iloc[:-1]

    # Remove timestamp column if it exists
    if "timestamp" in data.columns:
        del data["timestamp"]

    return data

In [231]:
def run_tp_sl(data, leverage=1, tp=0.015, sl=-0.015, cost=0.00, stock="TSLA"):
    """
    :params (mandatory): data (must contain High_time and Low_time columns)
    :params (optional): leverage=1, tp=0.015, sl=-0.015, cost=0.00
    :return: data with three new columns: Low_time (TimeStamp), High_time (TimeStamp), High_first (Boolean)
    """
    
    # Define the stock column names based on the stock ticker passed
    open_col = f"Open_{stock}"
    high_col = f"High_{stock}"
    low_col = f"Low_{stock}"
    
    # If the columns need to be converted to UTC, use tz_convert
# Handle mixed tz-naive and tz-aware data
    if data['Low_time'].dt.tz is None:
        data['Low_time'] = data['Low_time'].dt.tz_localize('UTC')
    if data['High_time'].dt.tz is None:
        data['High_time'] = data['High_time'].dt.tz_localize('UTC')



    
    
    # Initialize parameters
    buy = False
    sell = False
    data["duration"] = 0

    for i in range(len(data)):
        # Extract current row
        row = data.iloc[i]

        ######## OPEN BUY ########
        if not buy and row["Signal"] == 1:
            buy = True
            open_buy_price = row[open_col]
            open_buy_date = row.name

        # Verify conditions for buy trades
        if buy:
            var_buy_high = (row[high_col] - open_buy_price) / open_buy_price
            var_buy_low = (row[low_col] - open_buy_price) / open_buy_price

            # Check for both TP and SL on the same candle
            if var_buy_high > tp and var_buy_low < sl:
                if row["Low_time"] == row["High_time"]:
                    pass
                elif row["First"] == 2:
                    data.loc[row.name, "returns"] = tp * leverage
                    # Ensure open_buy_date is not None before calculating duration
                    if open_buy_date is not None:
                        data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()
                    else:
                        data.loc[row.name, "duration"] = None  # Or set to a default value


                elif row["First"] == 1:
                    data.loc[row.name, "returns"] = sl * leverage
                    # Ensure open_buy_date is not None before calculating duration
                    if open_buy_date is not None:
                        data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()
                    else:
                        data.loc[row.name, "duration"] = None  # Or set to a default value


                buy = False
                open_buy_price = None
                var_buy_high = 0
                var_buy_low = 0
                open_buy_date = None
            elif var_buy_high > tp:
                data.loc[row.name, "returns"] = tp * leverage
                # Ensure open_buy_date is not None before calculating duration
                if open_buy_date is not None:
                    data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()
                else:
                    data.loc[row.name, "duration"] = None  # Or set to a default value


                buy = False
                open_buy_price = None
                var_buy_high = 0
                var_buy_low = 0
                open_buy_date = None
            elif var_buy_low < sl:
                data.loc[row.name, "returns"] = sl * leverage
                # Ensure open_buy_date is not None before calculating duration
                if open_buy_date is not None:
                    data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()
                else:
                    data.loc[row.name, "duration"] = None  # Or set to a default value


                buy = False
                open_buy_price = None
                var_buy_high = 0
                var_buy_low = 0
                open_buy_date = None

        ######## OPEN SELL ########
        if not sell and row["Signal"] == -1:
            sell = True
            open_sell_price = row[open_col]
            open_sell_date = row.name

        # Verify conditions for sell trades
        if sell:
            var_sell_high = -(row[high_col] - open_sell_price) / open_sell_price
            var_sell_low = -(row[low_col] - open_sell_price) / open_sell_price

            if var_sell_low > tp and var_sell_high < sl:
                if row["Low_time"] == row["High_time"]:
                    pass
                elif row["First"] == 1:
                    data.loc[row.name, "returns"] = tp * leverage
                    data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()

                elif row["First"] == 2:
                    data.loc[row.name, "returns"] = sl * leverage
                    data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()

                sell = False
                open_sell_price = None
                var_sell_high = 0
                var_sell_low = 0
                open_sell_date = None
            elif var_sell_low > tp:
                data.loc[row.name, "returns"] = tp * leverage
                # Ensure open_buy_date is not None before calculating duration
                if open_buy_date is not None:
                    data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()
                else:
                    data.loc[row.name, "duration"] = None  # Or set to a default value


                sell = False
                open_sell_price = None
                var_sell_high = 0
                var_sell_low = 0
                open_sell_date = None
            elif var_sell_high < sl:
                data.loc[row.name, "returns"] = sl * leverage
                # Ensure open_buy_date is not None before calculating duration
                if open_buy_date is not None:
                    data.loc[row.name, "duration"] = (row.Low_time - open_buy_date).total_seconds()
                else:
                    data.loc[row.name, "duration"] = None  # Or set to a default value

                sell = False
                open_sell_price = None
                var_sell_high = 0
                var_sell_low = 0
                open_sell_date = None

    # Fill missing returns with 0
    data["returns"] = data["returns"].fillna(value=0)
    return data

In [232]:
import yfinance as yf
import pandas as pd

def resample_ohlcv_data(data_ohlcv, high_timeframe='1h', low_timeframe='15min'):
    """
    Resample OHLCV data for multiple stocks with a generic approach
    
    Parameters:
    -----------
    data_ohlcv : pandas.DataFrame
        Multi-level column DataFrame with OHLCV data
    high_timeframe : str, optional (default='1h')
        Timeframe for higher resolution resampling
    low_timeframe : str, optional (default='15min')
        Timeframe for lower resolution resampling
    
    Returns:
    --------
    tuple : (high_timeframe_data, low_timeframe_data)
    """
    # Get all unique stock tickers
    stocks = set([col[1] for col in data_ohlcv.columns])
    
    # Prepare aggregation dictionaries
    agg_methods = {
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
        'Adj Close': 'last',
        'Volume': 'sum'
    }
    
    # Create resampled dataframes for each timeframe
    resampled_data = {}
    for timeframe in [high_timeframe, low_timeframe]:
        # Prepare aggregation dictionary for all stocks
        agg_dict = {}
        for stock in stocks:
            for col, method in agg_methods.items():
                full_col_name = (col, stock)
                agg_dict[full_col_name] = method
        
        # Resample the data
        resampled = data_ohlcv.resample(timeframe).agg(agg_dict).dropna()
        
        # Flatten column names if needed
        resampled.columns = ['_'.join(col).strip() for col in resampled.columns]
        
        resampled_data[timeframe] = resampled
    
    return resampled_data[high_timeframe], resampled_data[low_timeframe]


high_timeframe_data, low_timeframe_data = resample_ohlcv_data(data_ohlcv)

# Print the first few rows of each
print("High Timeframe Data:")
print(high_timeframe_data.head())
print("\nLow Timeframe Data:")
print(low_timeframe_data.head())

High Timeframe Data:
                           Open_TSLA  High_TSLA  Low_TSLA  Close_TSLA  \
Date
2012-05-18 00:00:00+00:00   1.891333   1.897333  1.788667    1.837333
2012-05-21 00:00:00+00:00   1.838667   1.950667  1.808000    1.918000
2012-05-22 00:00:00+00:00   2.006667   2.089333  2.000000    2.053333
2012-05-23 00:00:00+00:00   2.037333   2.070000  1.966667    2.068000
2012-05-24 00:00:00+00:00   2.083333   2.083333  1.979333    2.018667

                           Adj Close_TSLA  Volume_TSLA  Open_META  High_META  \
Date
2012-05-18 00:00:00+00:00        1.837333     24247500  42.049999  45.000000
2012-05-21 00:00:00+00:00        1.918000     22128000  36.529999  36.660000
2012-05-22 00:00:00+00:00        2.053333     35493000  32.610001  33.590000
2012-05-23 00:00:00+00:00        2.068000     18306000  31.370001  32.500000
2012-05-24 00:00:00+00:00        2.018667     16134000  32.950001  33.209999

                            Low_META  Close_META  Adj Close_META  Volume_META  \
Date
2012-05-18 00:00:00+00:00  38.000000   38.230000       38.115238  573576400.0
2012-05-21 00:00:00+00:00  33.000000   34.029999       33.927845  168192700.0
2012-05-22 00:00:00+00:00  30.940001   31.000000       30.906942  101786600.0
2012-05-23 00:00:00+00:00  31.360001   32.000000       31.903942   73600000.0
2012-05-24 00:00:00+00:00  31.770000   33.029999       32.930851   50237200.0

                           Open_NFLX  High_NFLX  Low_NFLX  Close_NFLX  \
Date
2012-05-18 00:00:00+00:00  10.328571  10.392857  9.337143    9.994286
2012-05-21 00:00:00+00:00   9.978571  10.312857  9.650000   10.248571
2012-05-22 00:00:00+00:00  10.257143  10.342857  9.607143    9.672857
2012-05-23 00:00:00+00:00   9.638571  10.307143  9.595714   10.272857
2012-05-24 00:00:00+00:00  10.217143  10.241429  9.928571   10.038571

                           Adj Close_NFLX  Volume_NFLX
Date
2012-05-18 00:00:00+00:00        9.994286     29415400
2012-05-21 00:00:00+00:00       10.248571     25143300
2012-05-22 00:00:00+00:00        9.672857     40014800
2012-05-23 00:00:00+00:00       10.272857     44100000
2012-05-24 00:00:00+00:00       10.038571     20742400

Low Timeframe Data:
                           Open_TSLA  High_TSLA  Low_TSLA  Close_TSLA  \
Date
2012-05-18 00:00:00+00:00   1.891333   1.897333  1.788667    1.837333
2012-05-21 00:00:00+00:00   1.838667   1.950667  1.808000    1.918000
2012-05-22 00:00:00+00:00   2.006667   2.089333  2.000000    2.053333
2012-05-23 00:00:00+00:00   2.037333   2.070000  1.966667    2.068000
2012-05-24 00:00:00+00:00   2.083333   2.083333  1.979333    2.018667

                           Adj Close_TSLA  Volume_TSLA  Open_META  High_META  \
Date
2012-05-18 00:00:00+00:00        1.837333     24247500  42.049999  45.000000
2012-05-21 00:00:00+00:00        1.918000     22128000  36.529999  36.660000
2012-05-22 00:00:00+00:00        2.053333     35493000  32.610001  33.590000
2012-05-23 00:00:00+00:00        2.068000     18306000  31.370001  32.500000
2012-05-24 00:00:00+00:00        2.018667     16134000  32.950001  33.209999

                            Low_META  Close_META  Adj Close_META  Volume_META  \
Date
2012-05-18 00:00:00+00:00  38.000000   38.230000       38.115238  573576400.0
2012-05-21 00:00:00+00:00  33.000000   34.029999       33.927845  168192700.0
2012-05-22 00:00:00+00:00  30.940001   31.000000       30.906942  101786600.0
2012-05-23 00:00:00+00:00  31.360001   32.000000       31.903942   73600000.0
2012-05-24 00:00:00+00:00  31.770000   33.029999       32.930851   50237200.0

                           Open_NFLX  High_NFLX  Low_NFLX  Close_NFLX  \
Date
2012-05-18 00:00:00+00:00  10.328571  10.392857  9.337143    9.994286
2012-05-21 00:00:00+00:00   9.978571  10.312857  9.650000   10.248571
2012-05-22 00:00:00+00:00  10.257143  10.342857  9.607143    9.672857
2012-05-23 00:00:00+00:00   9.638571  10.307143  9.595714   10.272857
2012-05-24 00:00:00+00:00  10.217143  10.241429  9.928571   10.038571

                           Adj Close_NFLX  Volume_NFLX
Date
2012-05-18 00:00:00+00:00        9.994286     29415400
2012-05-21 00:00:00+00:00       10.248571     25143300
2012-05-22 00:00:00+00:00        9.672857     40014800
2012-05-23 00:00:00+00:00       10.272857     44100000
2012-05-24 00:00:00+00:00       10.038571     20742400

In [233]:
print(find_timestamp_extremum(high_timeframe_data, low_timeframe_data))

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2419/2419 [00:48<00:00, 49.74it/s]

WARNINGS: Garbage row: 99.96%
                            Open_TSLA   High_TSLA    Low_TSLA  Close_TSLA  \
Date
2012-05-18 00:00:00+00:00    1.891333    1.897333    1.788667    1.837333
2012-05-21 00:00:00+00:00    1.838667    1.950667    1.808000    1.918000
2012-05-22 00:00:00+00:00    2.006667    2.089333    2.000000    2.053333
2012-05-23 00:00:00+00:00    2.037333    2.070000    1.966667    2.068000
2012-05-24 00:00:00+00:00    2.083333    2.083333    1.979333    2.018667
...                               ...         ...         ...         ...
2021-12-21 00:00:00+00:00  305.623322  313.166656  295.373322  312.843323
2021-12-22 00:00:00+00:00  321.886658  338.553345  319.016663  336.290009
2021-12-23 00:00:00+00:00  335.600006  357.660004  332.519989  355.666656
2021-12-27 00:00:00+00:00  357.890015  372.333344  356.906677  364.646667
2021-12-28 00:00:00+00:00  369.829987  373.000000  359.473328  362.823334

                           Adj Close_TSLA  Volume_TSLA   Open_META  \
Date
2012-05-18 00:00:00+00:00        1.837333     24247500   42.049999
2012-05-21 00:00:00+00:00        1.918000     22128000   36.529999
2012-05-22 00:00:00+00:00        2.053333     35493000   32.610001
2012-05-23 00:00:00+00:00        2.068000     18306000   31.370001
2012-05-24 00:00:00+00:00        2.018667     16134000   32.950001
...                                   ...          ...         ...
2021-12-21 00:00:00+00:00      312.843323     71517900  326.410004
2021-12-22 00:00:00+00:00      336.290009     93634200  333.799988
2021-12-23 00:00:00+00:00      355.666656     92713200  330.100006
2021-12-27 00:00:00+00:00      364.646667     71145900  338.850006
2021-12-28 00:00:00+00:00      362.823334     60324000  346.630005

                            High_META    Low_META  Close_META  ...  \
Date                                                           ...
2012-05-18 00:00:00+00:00   45.000000   38.000000   38.230000  ...
2012-05-21 00:00:00+00:00   36.660000   33.000000   34.029999  ...
2012-05-22 00:00:00+00:00   33.590000   30.940001   31.000000  ...
2012-05-23 00:00:00+00:00   32.500000   31.360001   32.000000  ...
2012-05-24 00:00:00+00:00   33.209999   31.770000   33.029999  ...
...                               ...         ...         ...  ...
2021-12-21 00:00:00+00:00  336.000000  323.750000  334.200012  ...
2021-12-22 00:00:00+00:00  334.510010  328.260010  330.450012  ...
2021-12-23 00:00:00+00:00  336.670013  328.359985  335.239990  ...
2021-12-27 00:00:00+00:00  347.869995  338.010010  346.179993  ...
2021-12-28 00:00:00+00:00  352.709991  345.200012  346.220001  ...

                           Volume_META   Open_NFLX   High_NFLX    Low_NFLX  \
Date
2012-05-18 00:00:00+00:00  573576400.0   10.328571   10.392857    9.337143
2012-05-21 00:00:00+00:00  168192700.0    9.978571   10.312857    9.650000
2012-05-22 00:00:00+00:00  101786600.0   10.257143   10.342857    9.607143
2012-05-23 00:00:00+00:00   73600000.0    9.638571   10.307143    9.595714
2012-05-24 00:00:00+00:00   50237200.0   10.217143   10.241429    9.928571
...                                ...         ...         ...         ...
2021-12-21 00:00:00+00:00   16116800.0  597.539978  607.820007  593.859985
2021-12-22 00:00:00+00:00   16764600.0  603.359985  614.820007  602.630005
2021-12-23 00:00:00+00:00   13987700.0  616.400024  616.880005  607.570007
2021-12-27 00:00:00+00:00   17795000.0  615.000000  615.000000  609.250000
2021-12-28 00:00:00+00:00   16637600.0  614.950012  618.409973  609.690002

                           Close_NFLX  Adj Close_NFLX  Volume_NFLX   Low_time  \
Date
2012-05-18 00:00:00+00:00    9.994286        9.994286     29415400 2012-05-18
2012-05-21 00:00:00+00:00   10.248571       10.248571     25143300 2012-05-21
2012-05-22 00:00:00+00:00    9.672857        9.672857     40014800 2012-05-22
2012-05-23 00:00:00+00:00   10.272857       10.272857     44100000 2012-05-23
2012-05-24 00:00:00+00:00   10.038571       10.038571     20742400 2012-05-24
...                               ...             ...          ...        ...
2021-12-21 00:00:00+00:00  604.919983      604.919983      2319400 2021-12-21
2021-12-22 00:00:00+00:00  614.239990      614.239990      2335700 2021-12-22
2021-12-23 00:00:00+00:00  614.090027      614.090027      1621100 2021-12-23
2021-12-27 00:00:00+00:00  613.119995      613.119995      2061500 2021-12-27
2021-12-28 00:00:00+00:00  610.710022      610.710022      1882800 2021-12-28

                           High_time First
Date
2012-05-18 00:00:00+00:00 2012-05-18   0.0
2012-05-21 00:00:00+00:00 2012-05-21   0.0
2012-05-22 00:00:00+00:00 2012-05-22   0.0
2012-05-23 00:00:00+00:00 2012-05-23   0.0
2012-05-24 00:00:00+00:00 2012-05-24   0.0
...                              ...   ...
2021-12-21 00:00:00+00:00 2021-12-21   0.0
2021-12-22 00:00:00+00:00 2021-12-22   0.0
2021-12-23 00:00:00+00:00 2021-12-23   0.0
2021-12-27 00:00:00+00:00 2021-12-27   0.0
2021-12-28 00:00:00+00:00 2021-12-28   0.0

[2419 rows x 21 columns]

In [234]:
result = find_timestamp_extremum(high_timeframe_data, low_timeframe_data)
print("New Columns Added:")
print("Low_time column exists:", 'Low_time' in result.columns)
print("High_time column exists:", 'High_time' in result.columns)
print("First column exists:", 'First' in result.columns)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2419/2419 [00:01<00:00, 1319.35it/s]

WARNINGS: Garbage row: 99.96%
New Columns Added:
Low_time column exists: True
High_time column exists: True
First column exists: True

In [235]:
import numpy as np

# Set the random seed for reproducibility
np.random.seed(70)

# Define possible signal values and their probabilities
values = [-1, 0, 1]
probabilities = [0.10, 0.80, 0.10]

# Generate random signals and assign them to the 'Signal' column in the DataFrame
result['Signal'] = np.random.choice(values, p=probabilities, size=len(result))

print(run_tp_sl(result, leverage=1, tp=0.015, sl=-0.015, cost=0.00))
# print(result.columns)

                            Open_TSLA   High_TSLA    Low_TSLA  Close_TSLA  \
Date
2012-05-18 00:00:00+00:00    1.891333    1.897333    1.788667    1.837333
2012-05-21 00:00:00+00:00    1.838667    1.950667    1.808000    1.918000
2012-05-22 00:00:00+00:00    2.006667    2.089333    2.000000    2.053333
2012-05-23 00:00:00+00:00    2.037333    2.070000    1.966667    2.068000
2012-05-24 00:00:00+00:00    2.083333    2.083333    1.979333    2.018667
...                               ...         ...         ...         ...
2021-12-21 00:00:00+00:00  305.623322  313.166656  295.373322  312.843323
2021-12-22 00:00:00+00:00  321.886658  338.553345  319.016663  336.290009
2021-12-23 00:00:00+00:00  335.600006  357.660004  332.519989  355.666656
2021-12-27 00:00:00+00:00  357.890015  372.333344  356.906677  364.646667
2021-12-28 00:00:00+00:00  369.829987  373.000000  359.473328  362.823334

                           Adj Close_TSLA  Volume_TSLA   Open_META  \
Date
2012-05-18 00:00:00+00:00        1.837333     24247500   42.049999
2012-05-21 00:00:00+00:00        1.918000     22128000   36.529999
2012-05-22 00:00:00+00:00        2.053333     35493000   32.610001
2012-05-23 00:00:00+00:00        2.068000     18306000   31.370001
2012-05-24 00:00:00+00:00        2.018667     16134000   32.950001
...                                   ...          ...         ...
2021-12-21 00:00:00+00:00      312.843323     71517900  326.410004
2021-12-22 00:00:00+00:00      336.290009     93634200  333.799988
2021-12-23 00:00:00+00:00      355.666656     92713200  330.100006
2021-12-27 00:00:00+00:00      364.646667     71145900  338.850006
2021-12-28 00:00:00+00:00      362.823334     60324000  346.630005

                            High_META    Low_META  Close_META  ...  \
Date                                                           ...
2012-05-18 00:00:00+00:00   45.000000   38.000000   38.230000  ...
2012-05-21 00:00:00+00:00   36.660000   33.000000   34.029999  ...
2012-05-22 00:00:00+00:00   33.590000   30.940001   31.000000  ...
2012-05-23 00:00:00+00:00   32.500000   31.360001   32.000000  ...
2012-05-24 00:00:00+00:00   33.209999   31.770000   33.029999  ...
...                               ...         ...         ...  ...
2021-12-21 00:00:00+00:00  336.000000  323.750000  334.200012  ...
2021-12-22 00:00:00+00:00  334.510010  328.260010  330.450012  ...
2021-12-23 00:00:00+00:00  336.670013  328.359985  335.239990  ...
2021-12-27 00:00:00+00:00  347.869995  338.010010  346.179993  ...
2021-12-28 00:00:00+00:00  352.709991  345.200012  346.220001  ...

                             Low_NFLX  Close_NFLX  Adj Close_NFLX  \
Date
2012-05-18 00:00:00+00:00    9.337143    9.994286        9.994286
2012-05-21 00:00:00+00:00    9.650000   10.248571       10.248571
2012-05-22 00:00:00+00:00    9.607143    9.672857        9.672857
2012-05-23 00:00:00+00:00    9.595714   10.272857       10.272857
2012-05-24 00:00:00+00:00    9.928571   10.038571       10.038571
...                               ...         ...             ...
2021-12-21 00:00:00+00:00  593.859985  604.919983      604.919983
2021-12-22 00:00:00+00:00  602.630005  614.239990      614.239990
2021-12-23 00:00:00+00:00  607.570007  614.090027      614.090027
2021-12-27 00:00:00+00:00  609.250000  613.119995      613.119995
2021-12-28 00:00:00+00:00  609.690002  610.710022      610.710022

                           Volume_NFLX                  Low_time  \
Date
2012-05-18 00:00:00+00:00     29415400 2012-05-18 00:00:00+00:00
2012-05-21 00:00:00+00:00     25143300 2012-05-21 00:00:00+00:00
2012-05-22 00:00:00+00:00     40014800 2012-05-22 00:00:00+00:00
2012-05-23 00:00:00+00:00     44100000 2012-05-23 00:00:00+00:00
2012-05-24 00:00:00+00:00     20742400 2012-05-24 00:00:00+00:00
...                                ...                       ...
2021-12-21 00:00:00+00:00      2319400 2021-12-21 00:00:00+00:00
2021-12-22 00:00:00+00:00      2335700 2021-12-22 00:00:00+00:00
2021-12-23 00:00:00+00:00      1621100 2021-12-23 00:00:00+00:00
2021-12-27 00:00:00+00:00      2061500 2021-12-27 00:00:00+00:00
2021-12-28 00:00:00+00:00      1882800 2021-12-28 00:00:00+00:00

                                          High_time  First  Signal duration  \
Date
2012-05-18 00:00:00+00:00 2012-05-18 00:00:00+00:00    0.0       1      0.0
2012-05-21 00:00:00+00:00 2012-05-21 00:00:00+00:00    0.0       0      0.0
2012-05-22 00:00:00+00:00 2012-05-22 00:00:00+00:00    0.0       0      0.0
2012-05-23 00:00:00+00:00 2012-05-23 00:00:00+00:00    0.0       1      0.0
2012-05-24 00:00:00+00:00 2012-05-24 00:00:00+00:00    0.0       0      0.0
...                                             ...    ...     ...      ...
2021-12-21 00:00:00+00:00 2021-12-21 00:00:00+00:00    0.0       0      0.0
2021-12-22 00:00:00+00:00 2021-12-22 00:00:00+00:00    0.0       0      0.0
2021-12-23 00:00:00+00:00 2021-12-23 00:00:00+00:00    0.0       0      0.0
2021-12-27 00:00:00+00:00 2021-12-27 00:00:00+00:00    0.0       0      0.0
2021-12-28 00:00:00+00:00 2021-12-28 00:00:00+00:00    0.0       0      0.0

                          returns
Date
2012-05-18 00:00:00+00:00  -0.015
2012-05-21 00:00:00+00:00   0.000
2012-05-22 00:00:00+00:00   0.000
2012-05-23 00:00:00+00:00   0.000
2012-05-24 00:00:00+00:00   0.000
...                           ...
2021-12-21 00:00:00+00:00   0.000
2021-12-22 00:00:00+00:00   0.000
2021-12-23 00:00:00+00:00   0.000
2021-12-27 00:00:00+00:00   0.000
2021-12-28 00:00:00+00:00   0.000

[2419 rows x 24 columns]

In [236]:
selected_columns = result[['Signal', 'duration', 'returns']]
print(selected_columns)

                           Signal  duration  returns
Date
2012-05-18 00:00:00+00:00       1       0.0   -0.015
2012-05-21 00:00:00+00:00       0       0.0    0.000
2012-05-22 00:00:00+00:00       0       0.0    0.000
2012-05-23 00:00:00+00:00       1       0.0    0.000
2012-05-24 00:00:00+00:00       0       0.0    0.000
...                           ...       ...      ...
2021-12-21 00:00:00+00:00       0       0.0    0.000
2021-12-22 00:00:00+00:00       0       0.0    0.000
2021-12-23 00:00:00+00:00       0       0.0    0.000
2021-12-27 00:00:00+00:00       0       0.0    0.000
2021-12-28 00:00:00+00:00       0       0.0    0.000

[2419 rows x 3 columns]